# Generated by Django 2.1.2 on 2018-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisPerris', '0004_auto_20181029_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='bday',
            field=models.DateTimeField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
